// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CapacityCalculation struct {
	ID        pgtype.UUID
	Input     []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type ListingSnapshot struct {
	ID               pgtype.UUID
	CollectionRunID  pgtype.UUID
	NeighborhoodID   pgtype.UUID
	ListingPrice     pgtype.Numeric
	TransactionPrice pgtype.Numeric
	PriceCut         bool
	DaysOnMarket     int32
	Layout           string
	CapturedAt       pgtype.Timestamptz
}

type Neighborhood struct {
	ID           pgtype.UUID
	Name         string
	Area         string
	TargetLayout string
	CreatedAt    pgtype.Timestamptz
}

type NeighborhoodMetric struct {
	ID                  pgtype.UUID
	NeighborhoodID      pgtype.UUID
	ListedHomes         int32
	PriceCutHomes       int32
	AvgDaysOnMarket     pgtype.Numeric
	ListingPriceMin     pgtype.Numeric
	ListingPriceMax     pgtype.Numeric
	TransactionPriceMin pgtype.Numeric
	TransactionPriceMax pgtype.Numeric
	TransactionMomentum string
	TargetLayoutSupply  int32
	CalculatedAt        pgtype.Timestamptz
}

type RawCollectionRecord struct {
	ID          pgtype.UUID
	SourceType  string
	SourceRef   string
	Payload     []byte
	CollectedAt pgtype.Timestamptz
}

type WatchlistItem struct {
	ID             pgtype.UUID
	NeighborhoodID pgtype.UUID
	UserID         string
	CreatedAt      pgtype.Timestamptz
}
