// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CapacityCalculation struct {
	ID        pgtype.UUID
	UserID    string
	Input     []byte
	Result    []byte
	CreatedAt pgtype.Timestamptz
}

type CollectionRun struct {
	ID                pgtype.UUID
	DataSourceID      pgtype.UUID
	NeighborhoodID    pgtype.UUID
	SourceRef         string
	CollectedAt       pgtype.Timestamptz
	Coverage          string
	ImportFormat      string
	ContentChecksum   string
	RawPayload        []byte
	RawContentType    string
	ValidationSummary []byte
	Status            string
	MetricStatus      string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type DataSource struct {
	ID         pgtype.UUID
	Name       string
	SourceType string
	City       string
	Notes      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ListingObservation struct {
	ID              pgtype.UUID
	CollectionRunID pgtype.UUID
	NeighborhoodID  pgtype.UUID
	SourceListingID string
	SourceRow       int32
	Layout          string
	AreaSqm         pgtype.Numeric
	ListingPrice    pgtype.Numeric
	DaysOnMarket    int32
	Status          string
	CapturedAt      pgtype.Timestamptz
	Attributes      []byte
}

type Neighborhood struct {
	ID           pgtype.UUID
	Name         string
	Area         string
	TargetLayout string
	CreatedAt    pgtype.Timestamptz
}

type NeighborhoodMetric struct {
	ID                       pgtype.UUID
	NeighborhoodID           pgtype.UUID
	ListedHomes              int32
	PriceCutHomes            int32
	AvgDaysOnMarket          pgtype.Numeric
	ListingPriceMin          pgtype.Numeric
	ListingPriceMax          pgtype.Numeric
	TransactionPriceMin      pgtype.Numeric
	TransactionPriceMax      pgtype.Numeric
	TransactionMomentum      string
	TargetLayoutSupply       int32
	CalculatedAt             pgtype.Timestamptz
	CollectionRunID          pgtype.UUID
	InventoryCollectionRunID pgtype.UUID
	SourceIds                []byte
	ListingSampleCount       int32
	TransactionSampleCount   int32
	ListedHomesChangePct     pgtype.Numeric
	Coverage                 string
	Freshness                string
	QualityState             string
	LatestObservedAt         pgtype.Timestamptz
	InventoryCollectedAt     pgtype.Timestamptz
	QualityWarnings          []byte
}

type TransactionObservation struct {
	ID                 pgtype.UUID
	CollectionRunID    pgtype.UUID
	NeighborhoodID     pgtype.UUID
	SourceRecordID     string
	SourceRow          int32
	Layout             string
	AreaSqm            pgtype.Numeric
	TransactionPrice   pgtype.Numeric
	TransactionDate    pgtype.Date
	OriginalListingRef pgtype.Text
	CapturedAt         pgtype.Timestamptz
}

type WatchlistItem struct {
	ID             pgtype.UUID
	NeighborhoodID pgtype.UUID
	UserID         string
	CreatedAt      pgtype.Timestamptz
}
