// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: neighborhood_metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateMarketObservations = `-- name: AggregateMarketObservations :one
WITH trigger_run AS (
  SELECT id, data_source_id, neighborhood_id, collected_at, coverage
  FROM collection_runs
  WHERE collection_runs.id = $1
    AND collection_runs.neighborhood_id = $2
    AND collection_runs.status = 'completed'
),
inventory_run AS (
  SELECT cr.id, cr.data_source_id, cr.neighborhood_id, cr.collected_at, cr.coverage
  FROM collection_runs cr
  JOIN trigger_run tr ON tr.neighborhood_id = cr.neighborhood_id
  WHERE cr.status = 'completed'
    AND cr.coverage = 'full'
    AND (cr.collected_at, cr.id) <= (tr.collected_at, tr.id)
  ORDER BY cr.collected_at DESC, cr.id DESC
  LIMIT 1
),
previous_inventory_run AS (
  SELECT cr.id
  FROM collection_runs cr
  JOIN inventory_run ir ON ir.neighborhood_id = cr.neighborhood_id
  WHERE cr.status = 'completed'
    AND cr.coverage = 'full'
    AND (cr.collected_at, cr.id) < (ir.collected_at, ir.id)
  ORDER BY cr.collected_at DESC, cr.id DESC
  LIMIT 1
),
inventory_listings (
  id,
  collection_run_id,
  neighborhood_id,
  source_listing_id,
  source_row,
  listing_layout,
  area_sqm,
  listing_price,
  days_on_market,
  status,
  captured_at,
  attributes,
  data_source_id
) AS (
  SELECT
    lo.id,
    lo.collection_run_id,
    lo.neighborhood_id,
    lo.source_listing_id,
    lo.source_row,
    lo.layout AS listing_layout,
    lo.area_sqm,
    lo.listing_price,
    lo.days_on_market,
    lo.status,
    lo.captured_at,
    lo.attributes,
    ir.data_source_id
  FROM inventory_run ir
  JOIN listing_observations lo ON lo.collection_run_id = ir.id
  WHERE lo.status = 'active'
),
listing_aggregate AS (
  SELECT
    COUNT(*)::int AS listed_homes,
    AVG(days_on_market)::numeric AS avg_days_on_market,
    MIN(listing_price)::numeric AS listing_price_min,
    MAX(listing_price)::numeric AS listing_price_max,
    MAX(captured_at) AS latest_listing_observed_at
  FROM inventory_listings
),
layout_supply AS (
  SELECT COALESCE(
    jsonb_object_agg(layout, supply ORDER BY layout),
    '{}'::jsonb
  ) AS target_layout_supply_by_layout
  FROM (
    SELECT listing_layout AS layout, COUNT(*)::int AS supply
    FROM inventory_listings
    GROUP BY listing_layout
  ) grouped_supply
),
previous_listing_aggregate AS (
  SELECT COUNT(*)::int AS previous_listed_homes
  FROM previous_inventory_run pir
  JOIN listing_observations lo ON lo.collection_run_id = pir.id
  WHERE lo.status = 'active'
),
price_cut_aggregate AS (
  SELECT COUNT(*)::int AS price_cut_homes
  FROM inventory_listings current_listing
  JOIN trigger_run tr ON TRUE
  WHERE (
    SELECT prior_listing.listing_price
    FROM listing_observations prior_listing
    JOIN collection_runs prior_run ON prior_run.id = prior_listing.collection_run_id
    WHERE prior_run.status = 'completed'
      AND prior_run.data_source_id = current_listing.data_source_id
      AND prior_run.neighborhood_id = current_listing.neighborhood_id
      AND prior_listing.source_listing_id = current_listing.source_listing_id
      AND (prior_run.collected_at, prior_run.id) < (tr.collected_at, tr.id)
    ORDER BY prior_run.collected_at DESC, prior_run.id DESC, prior_listing.captured_at DESC
    LIMIT 1
  ) > current_listing.listing_price
),
latest_transactions AS (
  SELECT DISTINCT ON (cr.data_source_id, tx.source_record_id)
    tx.id, tx.collection_run_id, tx.neighborhood_id, tx.source_record_id, tx.source_row, tx.layout, tx.area_sqm, tx.transaction_price, tx.transaction_date, tx.original_listing_ref, tx.captured_at, cr.data_source_id
  FROM transaction_observations tx
  JOIN collection_runs cr ON cr.id = tx.collection_run_id
  JOIN trigger_run tr ON tr.neighborhood_id = tx.neighborhood_id
  WHERE cr.status = 'completed'
    AND cr.neighborhood_id = tr.neighborhood_id
    AND (cr.collected_at, cr.id) <= (tr.collected_at, tr.id)
    AND tx.transaction_date >= ((tr.collected_at AT TIME ZONE 'UTC')::date - 90)
    AND tx.transaction_date <= (tr.collected_at AT TIME ZONE 'UTC')::date
  ORDER BY cr.data_source_id, tx.source_record_id, cr.collected_at DESC, cr.id DESC, tx.captured_at DESC
),
transaction_aggregate AS (
  SELECT
    COUNT(*)::int AS transaction_sample_count,
    MIN(transaction_price)::numeric AS transaction_price_min,
    MAX(transaction_price)::numeric AS transaction_price_max,
    COUNT(*) FILTER (WHERE transaction_date > (SELECT (collected_at AT TIME ZONE 'UTC')::date - 30 FROM trigger_run))::int AS last_thirty_day_transaction_count,
    COUNT(*) FILTER (
      WHERE transaction_date <= (SELECT (collected_at AT TIME ZONE 'UTC')::date - 30 FROM trigger_run)
        AND transaction_date >= (SELECT (collected_at AT TIME ZONE 'UTC')::date - 90 FROM trigger_run)
    )::int AS preceding_sixty_day_transaction_count,
    MAX(captured_at) AS latest_transaction_observed_at
  FROM latest_transactions
),
source_ids AS (
  SELECT COALESCE(jsonb_agg(DISTINCT source_id ORDER BY source_id), '[]'::jsonb) AS source_ids
  FROM (
    SELECT data_source_id::text AS source_id FROM trigger_run
    UNION
    SELECT data_source_id::text AS source_id FROM inventory_listings
    UNION
    SELECT data_source_id::text AS source_id FROM latest_transactions
  ) s
)
SELECT
  tr.id AS collection_run_id,
  ir.id AS inventory_collection_run_id,
  source_ids.source_ids,
  COALESCE(GREATEST(la.latest_listing_observed_at, ta.latest_transaction_observed_at), tr.collected_at) AS latest_observed_at,
  ir.collected_at AS inventory_collected_at,
  tr.coverage AS coverage,
  COALESCE(la.listed_homes, 0)::int AS listed_homes,
  COALESCE(pca.price_cut_homes, 0)::int AS price_cut_homes,
  la.avg_days_on_market,
  la.listing_price_min,
  la.listing_price_max,
  ta.transaction_price_min,
  ta.transaction_price_max,
  ls.target_layout_supply_by_layout,
  COALESCE(la.listed_homes, 0)::int AS listing_sample_count,
  COALESCE(ta.transaction_sample_count, 0)::int AS transaction_sample_count,
  COALESCE(ta.last_thirty_day_transaction_count, 0)::int AS last_thirty_day_transaction_count,
  COALESCE(ta.preceding_sixty_day_transaction_count, 0)::int AS preceding_sixty_day_transaction_count,
  CASE
    WHEN pla.previous_listed_homes IS NULL OR pla.previous_listed_homes = 0 THEN NULL::numeric
    ELSE ((COALESCE(la.listed_homes, 0) - pla.previous_listed_homes)::numeric / pla.previous_listed_homes::numeric) * 100
  END AS listed_homes_change_pct
FROM trigger_run tr
CROSS JOIN source_ids
CROSS JOIN layout_supply ls
LEFT JOIN inventory_run ir ON TRUE
LEFT JOIN listing_aggregate la ON TRUE
LEFT JOIN previous_listing_aggregate pla ON TRUE
LEFT JOIN price_cut_aggregate pca ON TRUE
LEFT JOIN transaction_aggregate ta ON TRUE
`

type AggregateMarketObservationsParams struct {
	TriggerRunID   pgtype.UUID
	NeighborhoodID pgtype.UUID
}

type AggregateMarketObservationsRow struct {
	CollectionRunID                   pgtype.UUID
	InventoryCollectionRunID          pgtype.UUID
	SourceIds                         interface{}
	LatestObservedAt                  pgtype.Timestamptz
	InventoryCollectedAt              pgtype.Timestamptz
	Coverage                          string
	ListedHomes                       int32
	PriceCutHomes                     int32
	AvgDaysOnMarket                   pgtype.Numeric
	ListingPriceMin                   pgtype.Numeric
	ListingPriceMax                   pgtype.Numeric
	TransactionPriceMin               pgtype.Numeric
	TransactionPriceMax               pgtype.Numeric
	TargetLayoutSupplyByLayout        interface{}
	ListingSampleCount                int32
	TransactionSampleCount            int32
	LastThirtyDayTransactionCount     int32
	PrecedingSixtyDayTransactionCount int32
	ListedHomesChangePct              interface{}
}

func (q *Queries) AggregateMarketObservations(ctx context.Context, arg AggregateMarketObservationsParams) (AggregateMarketObservationsRow, error) {
	row := q.db.QueryRow(ctx, aggregateMarketObservations, arg.TriggerRunID, arg.NeighborhoodID)
	var i AggregateMarketObservationsRow
	err := row.Scan(
		&i.CollectionRunID,
		&i.InventoryCollectionRunID,
		&i.SourceIds,
		&i.LatestObservedAt,
		&i.InventoryCollectedAt,
		&i.Coverage,
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TargetLayoutSupplyByLayout,
		&i.ListingSampleCount,
		&i.TransactionSampleCount,
		&i.LastThirtyDayTransactionCount,
		&i.PrecedingSixtyDayTransactionCount,
		&i.ListedHomesChangePct,
	)
	return i, err
}

const getCompletedCollectionRun = `-- name: GetCompletedCollectionRun :one
SELECT id, data_source_id, neighborhood_id, collected_at, coverage, metric_status
FROM collection_runs
WHERE id = $1 AND status = 'completed'
`

type GetCompletedCollectionRunRow struct {
	ID             pgtype.UUID
	DataSourceID   pgtype.UUID
	NeighborhoodID pgtype.UUID
	CollectedAt    pgtype.Timestamptz
	Coverage       string
	MetricStatus   string
}

func (q *Queries) GetCompletedCollectionRun(ctx context.Context, id pgtype.UUID) (GetCompletedCollectionRunRow, error) {
	row := q.db.QueryRow(ctx, getCompletedCollectionRun, id)
	var i GetCompletedCollectionRunRow
	err := row.Scan(
		&i.ID,
		&i.DataSourceID,
		&i.NeighborhoodID,
		&i.CollectedAt,
		&i.Coverage,
		&i.MetricStatus,
	)
	return i, err
}

const latestCompletedCollectionRun = `-- name: LatestCompletedCollectionRun :one
SELECT id, data_source_id, neighborhood_id, collected_at, coverage, metric_status
FROM collection_runs
WHERE neighborhood_id = $1 AND status = 'completed'
ORDER BY collected_at DESC, id DESC
LIMIT 1
`

type LatestCompletedCollectionRunRow struct {
	ID             pgtype.UUID
	DataSourceID   pgtype.UUID
	NeighborhoodID pgtype.UUID
	CollectedAt    pgtype.Timestamptz
	Coverage       string
	MetricStatus   string
}

func (q *Queries) LatestCompletedCollectionRun(ctx context.Context, neighborhoodID pgtype.UUID) (LatestCompletedCollectionRunRow, error) {
	row := q.db.QueryRow(ctx, latestCompletedCollectionRun, neighborhoodID)
	var i LatestCompletedCollectionRunRow
	err := row.Scan(
		&i.ID,
		&i.DataSourceID,
		&i.NeighborhoodID,
		&i.CollectedAt,
		&i.Coverage,
		&i.MetricStatus,
	)
	return i, err
}

const latestCompletedFullCollectionRun = `-- name: LatestCompletedFullCollectionRun :one
SELECT id, data_source_id, neighborhood_id, collected_at, coverage, metric_status
FROM collection_runs
WHERE neighborhood_id = $1
  AND status = 'completed'
  AND coverage = 'full'
  AND (collected_at, id) <= ($2, $3::uuid)
ORDER BY collected_at DESC, id DESC
LIMIT 1
`

type LatestCompletedFullCollectionRunParams struct {
	NeighborhoodID     pgtype.UUID
	TriggerCollectedAt pgtype.Timestamptz
	TriggerRunID       pgtype.UUID
}

type LatestCompletedFullCollectionRunRow struct {
	ID             pgtype.UUID
	DataSourceID   pgtype.UUID
	NeighborhoodID pgtype.UUID
	CollectedAt    pgtype.Timestamptz
	Coverage       string
	MetricStatus   string
}

func (q *Queries) LatestCompletedFullCollectionRun(ctx context.Context, arg LatestCompletedFullCollectionRunParams) (LatestCompletedFullCollectionRunRow, error) {
	row := q.db.QueryRow(ctx, latestCompletedFullCollectionRun, arg.NeighborhoodID, arg.TriggerCollectedAt, arg.TriggerRunID)
	var i LatestCompletedFullCollectionRunRow
	err := row.Scan(
		&i.ID,
		&i.DataSourceID,
		&i.NeighborhoodID,
		&i.CollectedAt,
		&i.Coverage,
		&i.MetricStatus,
	)
	return i, err
}

const latestNeighborhoodMetric = `-- name: LatestNeighborhoodMetric :one
SELECT nm.id, nm.neighborhood_id, nm.listed_homes, nm.price_cut_homes, nm.avg_days_on_market, nm.listing_price_min, nm.listing_price_max, nm.transaction_price_min, nm.transaction_price_max, nm.transaction_momentum, nm.calculated_at, nm.collection_run_id, nm.inventory_collection_run_id, nm.source_ids, nm.listing_sample_count, nm.transaction_sample_count, nm.listed_homes_change_pct, nm.coverage, nm.freshness, nm.quality_state, nm.latest_observed_at, nm.inventory_collected_at, nm.quality_warnings, nm.algorithm_version, nm.transaction_window_start, nm.transaction_window_end, nm.recent_30_day_transaction_count, nm.preceding_60_day_transaction_count, nm.recent_30_day_monthly_frequency, nm.preceding_60_day_monthly_frequency, nm.target_layout_supply_by_layout, cr.collected_at AS collection_run_collected_at
FROM neighborhood_metrics nm
JOIN collection_runs cr ON cr.id = nm.collection_run_id
WHERE nm.neighborhood_id = $1
  AND nm.algorithm_version = $2
ORDER BY cr.collected_at DESC, cr.id DESC
LIMIT 1
`

type LatestNeighborhoodMetricParams struct {
	NeighborhoodID   pgtype.UUID
	AlgorithmVersion string
}

type LatestNeighborhoodMetricRow struct {
	ID                             pgtype.UUID
	NeighborhoodID                 pgtype.UUID
	ListedHomes                    int32
	PriceCutHomes                  int32
	AvgDaysOnMarket                pgtype.Numeric
	ListingPriceMin                pgtype.Numeric
	ListingPriceMax                pgtype.Numeric
	TransactionPriceMin            pgtype.Numeric
	TransactionPriceMax            pgtype.Numeric
	TransactionMomentum            string
	CalculatedAt                   pgtype.Timestamptz
	CollectionRunID                pgtype.UUID
	InventoryCollectionRunID       pgtype.UUID
	SourceIds                      []byte
	ListingSampleCount             int32
	TransactionSampleCount         int32
	ListedHomesChangePct           pgtype.Numeric
	Coverage                       string
	Freshness                      string
	QualityState                   string
	LatestObservedAt               pgtype.Timestamptz
	InventoryCollectedAt           pgtype.Timestamptz
	QualityWarnings                []byte
	AlgorithmVersion               string
	TransactionWindowStart         pgtype.Date
	TransactionWindowEnd           pgtype.Date
	Recent30DayTransactionCount    pgtype.Int4
	Preceding60DayTransactionCount pgtype.Int4
	Recent30DayMonthlyFrequency    pgtype.Numeric
	Preceding60DayMonthlyFrequency pgtype.Numeric
	TargetLayoutSupplyByLayout     []byte
	CollectionRunCollectedAt       pgtype.Timestamptz
}

func (q *Queries) LatestNeighborhoodMetric(ctx context.Context, arg LatestNeighborhoodMetricParams) (LatestNeighborhoodMetricRow, error) {
	row := q.db.QueryRow(ctx, latestNeighborhoodMetric, arg.NeighborhoodID, arg.AlgorithmVersion)
	var i LatestNeighborhoodMetricRow
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TransactionMomentum,
		&i.CalculatedAt,
		&i.CollectionRunID,
		&i.InventoryCollectionRunID,
		&i.SourceIds,
		&i.ListingSampleCount,
		&i.TransactionSampleCount,
		&i.ListedHomesChangePct,
		&i.Coverage,
		&i.Freshness,
		&i.QualityState,
		&i.LatestObservedAt,
		&i.InventoryCollectedAt,
		&i.QualityWarnings,
		&i.AlgorithmVersion,
		&i.TransactionWindowStart,
		&i.TransactionWindowEnd,
		&i.Recent30DayTransactionCount,
		&i.Preceding60DayTransactionCount,
		&i.Recent30DayMonthlyFrequency,
		&i.Preceding60DayMonthlyFrequency,
		&i.TargetLayoutSupplyByLayout,
		&i.CollectionRunCollectedAt,
	)
	return i, err
}

const listNeighborhoodMetricHistory = `-- name: ListNeighborhoodMetricHistory :many
SELECT
  nm.id, nm.neighborhood_id, nm.listed_homes, nm.price_cut_homes, nm.avg_days_on_market, nm.listing_price_min, nm.listing_price_max, nm.transaction_price_min, nm.transaction_price_max, nm.transaction_momentum, nm.calculated_at, nm.collection_run_id, nm.inventory_collection_run_id, nm.source_ids, nm.listing_sample_count, nm.transaction_sample_count, nm.listed_homes_change_pct, nm.coverage, nm.freshness, nm.quality_state, nm.latest_observed_at, nm.inventory_collected_at, nm.quality_warnings, nm.algorithm_version, nm.transaction_window_start, nm.transaction_window_end, nm.recent_30_day_transaction_count, nm.preceding_60_day_transaction_count, nm.recent_30_day_monthly_frequency, nm.preceding_60_day_monthly_frequency, nm.target_layout_supply_by_layout,
  cr.data_source_id,
  cr.source_ref,
  cr.collected_at AS collection_run_collected_at,
  cr.coverage AS collection_run_coverage
FROM neighborhood_metrics nm
JOIN collection_runs cr ON cr.id = nm.collection_run_id
WHERE nm.neighborhood_id = $1
  AND nm.algorithm_version = $2
  AND cr.collected_at >= $3
  AND cr.collected_at <= $4
ORDER BY cr.collected_at ASC, cr.id ASC
`

type ListNeighborhoodMetricHistoryParams struct {
	NeighborhoodID   pgtype.UUID
	AlgorithmVersion string
	CollectedFrom    pgtype.Timestamptz
	CollectedTo      pgtype.Timestamptz
}

type ListNeighborhoodMetricHistoryRow struct {
	ID                             pgtype.UUID
	NeighborhoodID                 pgtype.UUID
	ListedHomes                    int32
	PriceCutHomes                  int32
	AvgDaysOnMarket                pgtype.Numeric
	ListingPriceMin                pgtype.Numeric
	ListingPriceMax                pgtype.Numeric
	TransactionPriceMin            pgtype.Numeric
	TransactionPriceMax            pgtype.Numeric
	TransactionMomentum            string
	CalculatedAt                   pgtype.Timestamptz
	CollectionRunID                pgtype.UUID
	InventoryCollectionRunID       pgtype.UUID
	SourceIds                      []byte
	ListingSampleCount             int32
	TransactionSampleCount         int32
	ListedHomesChangePct           pgtype.Numeric
	Coverage                       string
	Freshness                      string
	QualityState                   string
	LatestObservedAt               pgtype.Timestamptz
	InventoryCollectedAt           pgtype.Timestamptz
	QualityWarnings                []byte
	AlgorithmVersion               string
	TransactionWindowStart         pgtype.Date
	TransactionWindowEnd           pgtype.Date
	Recent30DayTransactionCount    pgtype.Int4
	Preceding60DayTransactionCount pgtype.Int4
	Recent30DayMonthlyFrequency    pgtype.Numeric
	Preceding60DayMonthlyFrequency pgtype.Numeric
	TargetLayoutSupplyByLayout     []byte
	DataSourceID                   pgtype.UUID
	SourceRef                      string
	CollectionRunCollectedAt       pgtype.Timestamptz
	CollectionRunCoverage          string
}

func (q *Queries) ListNeighborhoodMetricHistory(ctx context.Context, arg ListNeighborhoodMetricHistoryParams) ([]ListNeighborhoodMetricHistoryRow, error) {
	rows, err := q.db.Query(ctx, listNeighborhoodMetricHistory,
		arg.NeighborhoodID,
		arg.AlgorithmVersion,
		arg.CollectedFrom,
		arg.CollectedTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNeighborhoodMetricHistoryRow
	for rows.Next() {
		var i ListNeighborhoodMetricHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.NeighborhoodID,
			&i.ListedHomes,
			&i.PriceCutHomes,
			&i.AvgDaysOnMarket,
			&i.ListingPriceMin,
			&i.ListingPriceMax,
			&i.TransactionPriceMin,
			&i.TransactionPriceMax,
			&i.TransactionMomentum,
			&i.CalculatedAt,
			&i.CollectionRunID,
			&i.InventoryCollectionRunID,
			&i.SourceIds,
			&i.ListingSampleCount,
			&i.TransactionSampleCount,
			&i.ListedHomesChangePct,
			&i.Coverage,
			&i.Freshness,
			&i.QualityState,
			&i.LatestObservedAt,
			&i.InventoryCollectedAt,
			&i.QualityWarnings,
			&i.AlgorithmVersion,
			&i.TransactionWindowStart,
			&i.TransactionWindowEnd,
			&i.Recent30DayTransactionCount,
			&i.Preceding60DayTransactionCount,
			&i.Recent30DayMonthlyFrequency,
			&i.Preceding60DayMonthlyFrequency,
			&i.TargetLayoutSupplyByLayout,
			&i.DataSourceID,
			&i.SourceRef,
			&i.CollectionRunCollectedAt,
			&i.CollectionRunCoverage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCollectionRunMetricCompleted = `-- name: MarkCollectionRunMetricCompleted :one
UPDATE collection_runs
SET metric_status = 'completed', updated_at = now()
WHERE id = $1 AND status = 'completed'
RETURNING id
`

func (q *Queries) MarkCollectionRunMetricCompleted(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markCollectionRunMetricCompleted, id)
	err := row.Scan(&id)
	return id, err
}

const upsertNeighborhoodMetric = `-- name: UpsertNeighborhoodMetric :one
INSERT INTO neighborhood_metrics (
  neighborhood_id,
  listed_homes,
  price_cut_homes,
  avg_days_on_market,
  listing_price_min,
  listing_price_max,
  transaction_price_min,
  transaction_price_max,
  transaction_momentum,
  target_layout_supply_by_layout,
  collection_run_id,
  inventory_collection_run_id,
  source_ids,
  listing_sample_count,
  transaction_sample_count,
  listed_homes_change_pct,
  coverage,
  freshness,
  quality_state,
  latest_observed_at,
  inventory_collected_at,
  quality_warnings,
  algorithm_version,
  transaction_window_start,
  transaction_window_end,
  recent_30_day_transaction_count,
  preceding_60_day_transaction_count,
  recent_30_day_monthly_frequency,
  preceding_60_day_monthly_frequency
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29
)
ON CONFLICT (collection_run_id, algorithm_version) DO UPDATE SET
  algorithm_version = neighborhood_metrics.algorithm_version
RETURNING id, neighborhood_id, listed_homes, price_cut_homes, avg_days_on_market, listing_price_min, listing_price_max, transaction_price_min, transaction_price_max, transaction_momentum, calculated_at, collection_run_id, inventory_collection_run_id, source_ids, listing_sample_count, transaction_sample_count, listed_homes_change_pct, coverage, freshness, quality_state, latest_observed_at, inventory_collected_at, quality_warnings, algorithm_version, transaction_window_start, transaction_window_end, recent_30_day_transaction_count, preceding_60_day_transaction_count, recent_30_day_monthly_frequency, preceding_60_day_monthly_frequency, target_layout_supply_by_layout
`

type UpsertNeighborhoodMetricParams struct {
	NeighborhoodID                 pgtype.UUID
	ListedHomes                    int32
	PriceCutHomes                  int32
	AvgDaysOnMarket                pgtype.Numeric
	ListingPriceMin                pgtype.Numeric
	ListingPriceMax                pgtype.Numeric
	TransactionPriceMin            pgtype.Numeric
	TransactionPriceMax            pgtype.Numeric
	TransactionMomentum            string
	TargetLayoutSupplyByLayout     []byte
	CollectionRunID                pgtype.UUID
	InventoryCollectionRunID       pgtype.UUID
	SourceIds                      []byte
	ListingSampleCount             int32
	TransactionSampleCount         int32
	ListedHomesChangePct           pgtype.Numeric
	Coverage                       string
	Freshness                      string
	QualityState                   string
	LatestObservedAt               pgtype.Timestamptz
	InventoryCollectedAt           pgtype.Timestamptz
	QualityWarnings                []byte
	AlgorithmVersion               string
	TransactionWindowStart         pgtype.Date
	TransactionWindowEnd           pgtype.Date
	Recent30DayTransactionCount    pgtype.Int4
	Preceding60DayTransactionCount pgtype.Int4
	Recent30DayMonthlyFrequency    pgtype.Numeric
	Preceding60DayMonthlyFrequency pgtype.Numeric
}

func (q *Queries) UpsertNeighborhoodMetric(ctx context.Context, arg UpsertNeighborhoodMetricParams) (NeighborhoodMetric, error) {
	row := q.db.QueryRow(ctx, upsertNeighborhoodMetric,
		arg.NeighborhoodID,
		arg.ListedHomes,
		arg.PriceCutHomes,
		arg.AvgDaysOnMarket,
		arg.ListingPriceMin,
		arg.ListingPriceMax,
		arg.TransactionPriceMin,
		arg.TransactionPriceMax,
		arg.TransactionMomentum,
		arg.TargetLayoutSupplyByLayout,
		arg.CollectionRunID,
		arg.InventoryCollectionRunID,
		arg.SourceIds,
		arg.ListingSampleCount,
		arg.TransactionSampleCount,
		arg.ListedHomesChangePct,
		arg.Coverage,
		arg.Freshness,
		arg.QualityState,
		arg.LatestObservedAt,
		arg.InventoryCollectedAt,
		arg.QualityWarnings,
		arg.AlgorithmVersion,
		arg.TransactionWindowStart,
		arg.TransactionWindowEnd,
		arg.Recent30DayTransactionCount,
		arg.Preceding60DayTransactionCount,
		arg.Recent30DayMonthlyFrequency,
		arg.Preceding60DayMonthlyFrequency,
	)
	var i NeighborhoodMetric
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TransactionMomentum,
		&i.CalculatedAt,
		&i.CollectionRunID,
		&i.InventoryCollectionRunID,
		&i.SourceIds,
		&i.ListingSampleCount,
		&i.TransactionSampleCount,
		&i.ListedHomesChangePct,
		&i.Coverage,
		&i.Freshness,
		&i.QualityState,
		&i.LatestObservedAt,
		&i.InventoryCollectedAt,
		&i.QualityWarnings,
		&i.AlgorithmVersion,
		&i.TransactionWindowStart,
		&i.TransactionWindowEnd,
		&i.Recent30DayTransactionCount,
		&i.Preceding60DayTransactionCount,
		&i.Recent30DayMonthlyFrequency,
		&i.Preceding60DayMonthlyFrequency,
		&i.TargetLayoutSupplyByLayout,
	)
	return i, err
}
