CREATE TABLE community_market_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  data_source_id UUID NOT NULL REFERENCES data_sources(id) ON DELETE RESTRICT,
  neighborhood_id UUID NOT NULL REFERENCES neighborhoods(id) ON DELETE CASCADE,
  source_ref TEXT NOT NULL CHECK (char_length(source_ref) BETWEEN 1 AND 256),
  collected_at TIMESTAMPTZ NOT NULL,
  content_checksum TEXT NOT NULL CHECK (content_checksum ~ '^[0-9a-f]{64}$'),
  raw_payload BYTEA NOT NULL,
  raw_content_type TEXT NOT NULL CHECK (char_length(raw_content_type) BETWEEN 1 AND 255),
  source_community_id TEXT NOT NULL CHECK (char_length(source_community_id) BETWEEN 1 AND 128),
  community_name TEXT NOT NULL CHECK (char_length(community_name) BETWEEN 1 AND 256),
  former_name TEXT NOT NULL DEFAULT '' CHECK (char_length(former_name) <= 256),
  city_code TEXT NOT NULL CHECK (char_length(city_code) BETWEEN 1 AND 32),
  city_name TEXT NOT NULL CHECK (char_length(city_name) BETWEEN 1 AND 128),
  district_code TEXT NOT NULL CHECK (char_length(district_code) BETWEEN 1 AND 32),
  district_name TEXT NOT NULL CHECK (char_length(district_name) BETWEEN 1 AND 128),
  block_code TEXT NOT NULL CHECK (char_length(block_code) BETWEEN 1 AND 64),
  block_name TEXT NOT NULL CHECK (char_length(block_name) BETWEEN 1 AND 128),
  latitude NUMERIC(10,7) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude NUMERIC(10,7) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  latest_listing_date DATE,
  listing_avg_unit_price NUMERIC(12,2) CHECK (listing_avg_unit_price >= 0),
  listing_count INT CHECK (listing_count >= 0),
  listing_area_sqm NUMERIC(14,2) CHECK (listing_area_sqm >= 0),
  listing_avg_total_price_wan NUMERIC(12,2) CHECK (listing_avg_total_price_wan >= 0),
  listing_avg_unit_price_6m NUMERIC(12,2) CHECK (listing_avg_unit_price_6m >= 0),
  new_listing_count_3m INT CHECK (new_listing_count_3m >= 0),
  new_listing_avg_total_price_3m_wan NUMERIC(12,2) CHECK (new_listing_avg_total_price_3m_wan >= 0),
  new_listing_unit_price_3m NUMERIC(12,2) CHECK (new_listing_unit_price_3m >= 0),
  latest_trade_date DATE,
  latest_trade_avg_unit_price NUMERIC(12,2) CHECK (latest_trade_avg_unit_price >= 0),
  trade_count_3m INT CHECK (trade_count_3m >= 0),
  trade_area_3m_sqm NUMERIC(14,2) CHECK (trade_area_3m_sqm >= 0),
  trade_avg_total_price_3m_wan NUMERIC(12,2) CHECK (trade_avg_total_price_3m_wan >= 0),
  trade_unit_price_3m NUMERIC(12,2) CHECK (trade_unit_price_3m >= 0),
  trade_avg_unit_price_6m NUMERIC(12,2) CHECK (trade_avg_unit_price_6m >= 0),
  trade_count_per_month_6m NUMERIC(10,2) CHECK (trade_count_per_month_6m >= 0),
  take_look_count INT CHECK (take_look_count >= 0),
  take_look_conversion_rate NUMERIC(7,4) CHECK (take_look_conversion_rate BETWEEN 0 AND 100),
  on_sale_area_range TEXT NOT NULL DEFAULT '' CHECK (char_length(on_sale_area_range) <= 128),
  on_sale_price_range TEXT NOT NULL DEFAULT '' CHECK (char_length(on_sale_price_range) <= 128),
  on_sale_room_types JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(on_sale_room_types) = 'array'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (data_source_id, source_ref, content_checksum)
);

CREATE INDEX idx_community_market_snapshots_neighborhood_collected_at
  ON community_market_snapshots(neighborhood_id, collected_at DESC, id DESC);
