// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: neighborhood_metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateListingSnapshots = `-- name: AggregateListingSnapshots :one
SELECT
  COUNT(*)::int AS listed_homes,
  COUNT(*) FILTER (WHERE price_cut)::int AS price_cut_homes,
  COALESCE(AVG(days_on_market), 0)::numeric AS avg_days_on_market,
  COALESCE(MIN(listing_price), 0)::numeric AS listing_price_min,
  COALESCE(MAX(listing_price), 0)::numeric AS listing_price_max,
  COALESCE(MIN(transaction_price), 0)::numeric AS transaction_price_min,
  COALESCE(MAX(transaction_price), 0)::numeric AS transaction_price_max,
  COUNT(*) FILTER (WHERE layout = $1)::int AS target_layout_supply
FROM listing_snapshots
WHERE neighborhood_id = $2
`

type AggregateListingSnapshotsParams struct {
	TargetLayout   string
	NeighborhoodID pgtype.UUID
}

type AggregateListingSnapshotsRow struct {
	ListedHomes         int32
	PriceCutHomes       int32
	AvgDaysOnMarket     pgtype.Numeric
	ListingPriceMin     pgtype.Numeric
	ListingPriceMax     pgtype.Numeric
	TransactionPriceMin pgtype.Numeric
	TransactionPriceMax pgtype.Numeric
	TargetLayoutSupply  int32
}

func (q *Queries) AggregateListingSnapshots(ctx context.Context, arg AggregateListingSnapshotsParams) (AggregateListingSnapshotsRow, error) {
	row := q.db.QueryRow(ctx, aggregateListingSnapshots, arg.TargetLayout, arg.NeighborhoodID)
	var i AggregateListingSnapshotsRow
	err := row.Scan(
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TargetLayoutSupply,
	)
	return i, err
}

const insertNeighborhoodMetric = `-- name: InsertNeighborhoodMetric :one
INSERT INTO neighborhood_metrics (
  neighborhood_id,
  listed_homes,
  price_cut_homes,
  avg_days_on_market,
  listing_price_min,
  listing_price_max,
  transaction_price_min,
  transaction_price_max,
  transaction_momentum,
  target_layout_supply
) VALUES (
  $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
)
RETURNING id, neighborhood_id, listed_homes, price_cut_homes, avg_days_on_market, listing_price_min, listing_price_max, transaction_price_min, transaction_price_max, transaction_momentum, target_layout_supply, calculated_at
`

type InsertNeighborhoodMetricParams struct {
	NeighborhoodID      pgtype.UUID
	ListedHomes         int32
	PriceCutHomes       int32
	AvgDaysOnMarket     pgtype.Numeric
	ListingPriceMin     pgtype.Numeric
	ListingPriceMax     pgtype.Numeric
	TransactionPriceMin pgtype.Numeric
	TransactionPriceMax pgtype.Numeric
	TransactionMomentum string
	TargetLayoutSupply  int32
}

func (q *Queries) InsertNeighborhoodMetric(ctx context.Context, arg InsertNeighborhoodMetricParams) (NeighborhoodMetric, error) {
	row := q.db.QueryRow(ctx, insertNeighborhoodMetric,
		arg.NeighborhoodID,
		arg.ListedHomes,
		arg.PriceCutHomes,
		arg.AvgDaysOnMarket,
		arg.ListingPriceMin,
		arg.ListingPriceMax,
		arg.TransactionPriceMin,
		arg.TransactionPriceMax,
		arg.TransactionMomentum,
		arg.TargetLayoutSupply,
	)
	var i NeighborhoodMetric
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TransactionMomentum,
		&i.TargetLayoutSupply,
		&i.CalculatedAt,
	)
	return i, err
}

const latestNeighborhoodMetric = `-- name: LatestNeighborhoodMetric :one
SELECT id, neighborhood_id, listed_homes, price_cut_homes, avg_days_on_market, listing_price_min, listing_price_max, transaction_price_min, transaction_price_max, transaction_momentum, target_layout_supply, calculated_at
FROM neighborhood_metrics
WHERE neighborhood_id = $1
ORDER BY calculated_at DESC
LIMIT 1
`

func (q *Queries) LatestNeighborhoodMetric(ctx context.Context, neighborhoodID pgtype.UUID) (NeighborhoodMetric, error) {
	row := q.db.QueryRow(ctx, latestNeighborhoodMetric, neighborhoodID)
	var i NeighborhoodMetric
	err := row.Scan(
		&i.ID,
		&i.NeighborhoodID,
		&i.ListedHomes,
		&i.PriceCutHomes,
		&i.AvgDaysOnMarket,
		&i.ListingPriceMin,
		&i.ListingPriceMax,
		&i.TransactionPriceMin,
		&i.TransactionPriceMax,
		&i.TransactionMomentum,
		&i.TargetLayoutSupply,
		&i.CalculatedAt,
	)
	return i, err
}
