/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the configured personal access token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Access token accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessStatusResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a housing capacity calculation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HousingCapacityInput"];
                };
            };
            responses: {
                /** @description Calculation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCalculationResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/calculations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a saved housing capacity calculation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calculation found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculationResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Calculation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a neighborhood */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNeighborhoodRequest"];
                };
            };
            responses: {
                /** @description Neighborhood created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a neighborhood */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest neighborhood metrics with signal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest metric found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodMetricResponse"];
                    };
                };
                /** @description Metric not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a neighborhood to the user's watchlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddWatchlistItemRequest"];
                };
            };
            responses: {
                /** @description Watchlist item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddWatchlistItemResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's watchlist */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WatchlistResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision/action-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend the current action window */
        get: {
            parameters: {
                query?: {
                    /** @description Neighborhood to evaluate. Defaults to the first watchlist item. */
                    neighborhoodId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action window recommendation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionWindowResponse"];
                    };
                };
                /** @description Request cannot produce an action window yet */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Neighborhood metric is not available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "metric_required",
                         *         "message": "no neighborhood metric is available"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trusted market data sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data sources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["DataSource"][];
                        };
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Data source operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create or resolve a trusted market data source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDataSourceRequest"];
                };
            };
            responses: {
                /** @description Data source created or resolved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSource"];
                    };
                };
                /** @description Malformed request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Data source fields are invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Data source operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a traceable JSON collection run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportJSONRequest"];
                };
            };
            responses: {
                /** @description Idempotent replay of an existing collection run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Collection run imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Selected source or neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Request body exceeds 2 MiB */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Import records failed semantic validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Import failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a traceable collection run and normalized observations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection run detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollectionRunDetail"];
                    };
                };
                /** @description Invalid collection run ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Collection run not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Import lookup failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HousingCapacityInput: {
            cashOnHand: number;
            oldHomeValue: number;
            oldLoanBalance: number;
            monthlyIncome: number;
            currentMonthlyMortgage: number;
            acceptableMonthlyMortgage: number;
            targetTotalPrice: number;
            renovationBudget: number;
            transactionCosts: number;
            transitionRentCost: number;
        };
        HousingCapacityResult: {
            netOldHomeProceeds: number;
            deployableCash: number;
            safeTotalPrice: number;
            strainedTotalPrice: number;
            dangerTotalPrice: number;
            downPaymentGap: number;
            monthlyPayment: number;
            monthlyPaymentRatio: number;
            /** @enum {string} */
            pressureLevel: "safe" | "strained" | "danger";
            minimumSafeOldHomeSalePrice: number;
            /** @enum {string} */
            strategy: "先卖后买或同步推进" | "可以同步推进" | "暂缓改善";
            reasons: string[];
            ruleVersion: string;
            effectiveDate: string;
        };
        CreateCalculationResponse: {
            id: string;
            result: {
                /** @enum {string} */
                pressureLevel: "safe" | "strained" | "danger";
                /** @enum {string} */
                strategy: "先卖后买或同步推进" | "可以同步推进" | "暂缓改善";
                ruleVersion: string;
                effectiveDate: string;
            };
        };
        CalculationResponse: {
            id: string;
            input: components["schemas"]["HousingCapacityInput"];
            result: components["schemas"]["HousingCapacityResult"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateNeighborhoodRequest: {
            name: string;
            area: string;
            targetLayout: string;
        };
        NeighborhoodResponse: {
            id: string;
            name: string;
            area: string;
            targetLayout: string;
            /** Format: date-time */
            createdAt?: string;
        };
        NeighborhoodMetricResponse: {
            id: string;
            neighborhoodId: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            inventoryCollectionRunId?: string;
            sourceIds: string[];
            /** Format: date-time */
            latestObservedAt: string;
            listedHomes: number;
            priceCutHomes: number;
            avgDaysOnMarket: number | null;
            listingPriceMin?: number | null;
            listingPriceMax?: number | null;
            transactionPriceMin?: number | null;
            transactionPriceMax?: number | null;
            /** @enum {string} */
            transactionMomentum: "unknown" | "weak" | "stable" | "strong";
            targetLayoutSupply: number;
            listingSampleCount: number;
            transactionSampleCount: number;
            /** @enum {string} */
            coverage: "full" | "partial";
            /** @enum {string} */
            freshness: "unknown" | "current" | "stale" | "expired";
            /** @enum {string} */
            qualityState: "sufficient" | "low_confidence" | "insufficient_data";
            qualityWarnings: string[];
            /** @enum {string} */
            status: "数据不足" | "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            /** @enum {string} */
            supplyPressure: "unknown" | "low" | "medium" | "high";
            priceCutShare?: number;
            priceGapPct?: number;
            /** @enum {string} */
            targetLayoutScarcity?: "unknown" | "low" | "medium" | "high";
            advice: string;
            reasons?: string[];
            /** Format: date-time */
            calculatedAt?: string;
        };
        AddWatchlistItemRequest: {
            neighborhoodId: string;
        };
        AddWatchlistItemResponse: {
            id: string;
            neighborhoodId: string;
            userId: string;
            /** Format: date-time */
            createdAt: string;
        };
        WatchlistResponse: {
            items: components["schemas"]["WatchlistItem"][];
        };
        WatchlistItem: {
            id: string;
            neighborhoodId: string;
            name: string;
            area: string;
            targetLayout: string;
            /** @enum {string} */
            status: "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            listedHomes: number;
            priceCutHomes: number;
            /** @enum {string} */
            transactionMomentum: "weak" | "stable" | "strong";
            advice: string;
        };
        ActionWindowResponse: {
            /**
             * @example 砍价
             * @enum {string}
             */
            action: "看" | "等" | "砍价" | "出手";
            /**
             * @example 高
             * @enum {string}
             */
            confidence: "低" | "中" | "高";
            /** @example 预算仍可服务，且目标小区供应与降价信号支持买方试探底价。 */
            summary: string;
            /**
             * @example [
             *       "约看 3 套成交区间附近、挂牌超过 60 天的目标户型。"
             *     ]
             */
            checklist: string[];
            /**
             * @example [
             *       "预算不是完全宽松，砍价失败时不要上调总价硬追。"
             *     ]
             */
            risks: string[];
        };
        AccessStatusResponse: {
            /** @enum {string} */
            status: "unlocked";
        };
        CreateDataSourceRequest: {
            name: string;
            sourceType: string;
            city: string;
            notes?: string;
        };
        DataSource: {
            /** Format: uuid */
            id: string;
            name: string;
            sourceType: string;
            city: string;
            notes: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ImportJSONRequest: {
            /** Format: uuid */
            dataSourceId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRef: string;
            /** Format: date-time */
            collectedAt: string;
            /** @enum {string} */
            coverage: "full" | "partial";
            records: components["schemas"]["ImportJSONRecord"][];
        };
        ImportJSONRecord: {
            /** @enum {string} */
            recordType: "listing" | "transaction";
            sourceRecordId: string;
            layout: string;
            areaSqm: number;
            listingPrice?: number;
            transactionPrice?: number;
            /** Format: date */
            transactionDate?: string;
            daysOnMarket?: number;
            /** @enum {string} */
            status?: "active" | "pending" | "withdrawn" | "sold";
            originalListingRef?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        CollectionRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dataSourceId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRef: string;
            /** Format: date-time */
            collectedAt: string;
            /** @enum {string} */
            coverage: "full" | "partial";
            /** @enum {string} */
            format: "json" | "csv";
            contentChecksum: string;
            rawContentType: string;
            validationSummary: components["schemas"]["ValidationSummary"];
            /** @enum {string} */
            status: "completed";
            /** @enum {string} */
            metricStatus: "pending" | "completed" | "failed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ValidationSummary: {
            recordCount: number;
            listingCount: number;
            transactionCount: number;
            issues: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            row?: number;
            field: string;
            code: string;
            message: string;
        };
        ImportCollectionRunResponse: {
            collectionRun: components["schemas"]["CollectionRun"];
            listingObservationCount: number;
            transactionObservationCount: number;
            idempotentReplay: boolean;
            /** @enum {string} */
            metricRefreshStatus: "pending" | "completed" | "failed";
        };
        ListingObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceListingId: string;
            sourceRow: number;
            layout: string;
            areaSqm: number;
            /** @description 万元 */
            listingPrice: number;
            daysOnMarket: number;
            /** @enum {string} */
            status: "active" | "pending" | "withdrawn" | "sold";
            /** Format: date-time */
            capturedAt: string;
            attributes: {
                [key: string]: string;
            };
        };
        TransactionObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRecordId: string;
            sourceRow: number;
            layout: string;
            areaSqm: number;
            /** @description 万元 */
            transactionPrice: number;
            /** Format: date */
            transactionDate: string;
            originalListingRef?: string;
            /** Format: date-time */
            capturedAt: string;
        };
        CollectionRunDetail: {
            collectionRun: components["schemas"]["CollectionRun"];
            source: components["schemas"]["DataSource"];
            listings: components["schemas"]["ListingObservation"][];
            transactions: components["schemas"]["TransactionObservation"][];
            /** Format: byte */
            rawPayloadBase64: string;
        };
        ValidationErrorResponse: {
            error: {
                /** @enum {string} */
                code: "validation_failed";
                message: string;
                details: components["schemas"]["ValidationIssue"][];
            };
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Valid bearer access token is required */
        AccessRequired: {
            headers: {
                /**
                 * @description Authentication scheme required to access this operation
                 * @example Bearer
                 */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "access_required",
                 *         "message": "valid bearer access token is required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
