/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capacity/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a housing capacity calculation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HousingCapacityInput"];
                };
            };
            responses: {
                /** @description Calculation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCalculationResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/calculations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a saved housing capacity calculation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calculation found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculationResponse"];
                    };
                };
                /** @description Calculation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a neighborhood */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNeighborhoodRequest"];
                };
            };
            responses: {
                /** @description Neighborhood created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a neighborhood */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest neighborhood metrics with signal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest metric found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodMetricResponse"];
                    };
                };
                /** @description Metric not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a neighborhood to the demo user's watchlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddWatchlistItemRequest"];
                };
            };
            responses: {
                /** @description Watchlist item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddWatchlistItemResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the demo user's watchlist */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WatchlistResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision/action-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend the current action window for the demo user */
        get: {
            parameters: {
                query?: {
                    /** @description Neighborhood to evaluate. Defaults to the first demo watchlist item. */
                    neighborhoodId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action window recommendation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionWindowResponse"];
                    };
                };
                /** @description Request cannot produce an action window yet */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Neighborhood metric is not available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "metric_required",
                         *         "message": "no neighborhood metric is available"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually import listing snapshots from JSON */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ManualImportRequest"];
                };
            };
            responses: {
                /** @description Listings imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManualImportResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Admin bearer token required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Admin bearer token invalid */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Import failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HousingCapacityInput: {
            cashOnHand: number;
            oldHomeValue: number;
            oldLoanBalance: number;
            monthlyIncome: number;
            currentMonthlyMortgage: number;
            acceptableMonthlyMortgage: number;
            targetTotalPrice: number;
            renovationBudget: number;
            transactionCosts: number;
            transitionRentCost: number;
        };
        HousingCapacityResult: {
            netOldHomeProceeds: number;
            deployableCash: number;
            safeTotalPrice: number;
            strainedTotalPrice: number;
            dangerTotalPrice: number;
            downPaymentGap: number;
            monthlyPayment: number;
            monthlyPaymentRatio: number;
            /** @enum {string} */
            pressureLevel: "safe" | "strained" | "danger";
            minimumSafeOldHomeSalePrice: number;
            /** @enum {string} */
            strategy: "先卖后买或同步推进" | "可以同步推进" | "暂缓改善";
            reasons: string[];
        };
        CreateCalculationResponse: {
            id: string;
            result: {
                /** @enum {string} */
                pressureLevel: "safe" | "strained" | "danger";
                /** @enum {string} */
                strategy: "先卖后买或同步推进" | "可以同步推进" | "暂缓改善";
            };
        };
        CalculationResponse: {
            id: string;
            input: components["schemas"]["HousingCapacityInput"];
            result: components["schemas"]["HousingCapacityResult"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateNeighborhoodRequest: {
            name: string;
            area: string;
            targetLayout: string;
        };
        NeighborhoodResponse: {
            id: string;
            name: string;
            area: string;
            targetLayout: string;
            /** Format: date-time */
            createdAt?: string;
        };
        NeighborhoodMetricResponse: {
            id: string;
            neighborhoodId: string;
            listedHomes: number;
            priceCutHomes: number;
            avgDaysOnMarket: number;
            listingPriceMin?: number;
            listingPriceMax?: number;
            transactionPriceMin?: number;
            transactionPriceMax?: number;
            /** @enum {string} */
            transactionMomentum: "weak" | "stable" | "strong";
            targetLayoutSupply: number;
            /** @enum {string} */
            status: "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            /** @enum {string} */
            supplyPressure: "low" | "medium" | "high";
            priceCutShare?: number;
            priceGapPct?: number;
            /** @enum {string} */
            targetLayoutScarcity?: "low" | "medium" | "high";
            advice: string;
            reasons?: string[];
            /** Format: date-time */
            calculatedAt?: string;
        };
        AddWatchlistItemRequest: {
            neighborhoodId: string;
        };
        AddWatchlistItemResponse: {
            id: string;
            neighborhoodId: string;
            userId: string;
            /** Format: date-time */
            createdAt: string;
        };
        WatchlistResponse: {
            items: components["schemas"]["WatchlistItem"][];
        };
        WatchlistItem: {
            id: string;
            neighborhoodId: string;
            name: string;
            area: string;
            targetLayout: string;
            /** @enum {string} */
            status: "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            listedHomes: number;
            priceCutHomes: number;
            /** @enum {string} */
            transactionMomentum: "weak" | "stable" | "strong";
            advice: string;
        };
        ActionWindowResponse: {
            /**
             * @example 砍价
             * @enum {string}
             */
            action: "看" | "等" | "砍价" | "出手";
            /**
             * @example 高
             * @enum {string}
             */
            confidence: "低" | "中" | "高";
            /** @example 预算仍可服务，且目标小区供应与降价信号支持买方试探底价。 */
            summary: string;
            /**
             * @example [
             *       "约看 3 套成交区间附近、挂牌超过 60 天的目标户型。"
             *     ]
             */
            checklist: string[];
            /**
             * @example [
             *       "预算不是完全宽松，砍价失败时不要上调总价硬追。"
             *     ]
             */
            risks: string[];
        };
        ManualImportRequest: {
            /** @enum {string} */
            sourceType: "manual_json";
            /** @example demo-weekly-import */
            sourceRef: string;
            /** Format: uuid */
            neighborhoodId: string;
            records: components["schemas"]["ManualImportRecord"][];
        };
        ManualImportRecord: {
            listingPrice: number;
            transactionPrice?: number | null;
            priceCut?: boolean;
            daysOnMarket: number;
            layout?: string;
        };
        ManualImportResponse: {
            /** Format: uuid */
            collectionRunId: string;
            importedSnapshotCount: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
