/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the configured personal access token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Access token accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessStatusResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get default calculation assumptions
         * @description Public. Returns the complete currently effective rule set used to pre-fill reproducible calculations.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default assumptions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapacityAssumptionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a housing capacity calculation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HousingCapacityInput"];
                };
            };
            responses: {
                /** @description Calculation created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateCalculationResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capacity/calculations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a saved housing capacity calculation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calculation found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalculationResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Calculation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search neighborhoods
         * @description Public, anonymous. Supports fuzzy query, area/layout filters and pagination.
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    area?: string;
                    targetLayout?: string;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matching neighborhoods */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodSearchResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a neighborhood */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNeighborhoodRequest"];
                };
            };
            responses: {
                /** @description Neighborhood created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a neighborhood */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Neighborhood found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest neighborhood metrics with signal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest metric found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NeighborhoodMetricResponse"];
                    };
                };
                /** @description Metric not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/neighborhoods/{id}/metrics/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current-algorithm neighborhood metric history and comparisons */
        get: {
            parameters: {
                query?: {
                    /** @description Inclusive collection-time lower bound. Defaults to eight weeks before `to`. */
                    from?: string;
                    /** @description Inclusive collection-time upper bound. Defaults to the current time. */
                    to?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metric history, including an explicit empty status when no points exist */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricHistoryResponse"];
                    };
                };
                /** @description Invalid or longer-than-52-week time window */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a neighborhood to the user's watchlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddWatchlistItemRequest"];
                };
            };
            responses: {
                /** @description Watchlist item created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddWatchlistItemResponse"];
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the user's watchlist */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watchlist items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WatchlistResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision/action-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommend the current action window */
        get: {
            parameters: {
                query?: {
                    /** @description Neighborhood to evaluate. Defaults to the first watchlist item. */
                    neighborhoodId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Action window recommendation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionWindowResponse"];
                    };
                };
                /** @description Request cannot produce an action window yet */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Neighborhood metric is not available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "metric_required",
                         *         "message": "no neighborhood metric is available"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description The latest metric exists but cannot support an action window */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trusted market data sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data sources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["DataSource"][];
                        };
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Data source operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create or resolve a trusted market data source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDataSourceRequest"];
                };
            };
            responses: {
                /** @description Data source created or resolved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSource"];
                    };
                };
                /** @description Malformed request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Data source fields are invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Data source operation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a traceable JSON collection run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportJSONRequest"];
                };
            };
            responses: {
                /** @description Idempotent replay of an existing collection run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Collection run imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Selected source or neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Request body exceeds 2 MiB */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Import records failed semantic validation */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportValidationErrorResponse"];
                    };
                };
                /** @description Import failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a traceable CSV collection run through the shared import pipeline */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: uuid */
                        dataSourceId: string;
                        /** Format: uuid */
                        neighborhoodId: string;
                        sourceRef: string;
                        /** Format: date-time */
                        collectedAt: string;
                        /** @enum {string} */
                        coverage: "full" | "partial";
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Idempotent replay of an existing collection run */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Collection run imported */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionRunResponse"];
                    };
                };
                /** @description Invalid multipart request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Selected source or neighborhood not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description CSV file or multipart request exceeds its size limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description CSV parsing or import semantic validation failed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportValidationErrorResponse"];
                    };
                };
                /** @description Import failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/csv/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the canonical UTF-8 CSV import template */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV header template */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                401: components["responses"]["AccessRequired"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a traceable collection run and normalized observations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection run detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollectionRunDetail"];
                    };
                };
                /** @description Invalid collection run ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["AccessRequired"];
                /** @description Collection run not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Import lookup failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HousingCapacityInput: {
            /** @description Available cash, in ten-thousand CNY. */
            cashOnHand: number;
            /** @description Expected old-home sale price, in ten-thousand CNY. */
            oldHomeValue: number;
            /** @description Outstanding old-home loan, in ten-thousand CNY. */
            oldLoanBalance: number;
            /** @description Monthly household income, in ten-thousand CNY. */
            monthlyIncome: number;
            /** @description Existing monthly mortgage, in ten-thousand CNY. */
            currentMonthlyMortgage: number;
            /** @description Maximum acceptable new monthly mortgage, in ten-thousand CNY. */
            acceptableMonthlyMortgage: number;
            /** @description Target home total price, in ten-thousand CNY. */
            targetTotalPrice: number;
            /** @description Renovation budget, in ten-thousand CNY. */
            renovationBudget: number;
            /** @description Taxes and transaction costs, in ten-thousand CNY. */
            transactionCosts: number;
            /** @description Transition rent and moving costs, in ten-thousand CNY. */
            transitionRentCost: number;
            loanOverride?: components["schemas"]["LoanParams"];
            cityPolicyOverride?: components["schemas"]["CityPolicyOverride"];
        };
        LoanParams: {
            annualInterestRate: number;
            loanTermMonths: number;
            /** @enum {string} */
            repaymentMethod: "equal_installment" | "equal_principal";
        };
        CityPolicyOverride: {
            city: string;
            policyName: string;
            downPaymentRate: number;
            /** Format: date */
            effectiveDate: string;
            source: string;
        };
        /** @enum {string} */
        AssumptionOrigin: "configured_default" | "user_override";
        CityPolicy: components["schemas"]["CityPolicyOverride"] & {
            origin: components["schemas"]["AssumptionOrigin"];
        };
        PressureThresholds: {
            safeRatio: number;
            strainedRatio: number;
            dangerRatio: number;
            dangerMultiplier: number;
        };
        AppliedAssumptions: {
            ruleVersion: string;
            /** Format: date */
            effectiveDate: string;
            ruleSource: string;
            loan: components["schemas"]["LoanParams"];
            loanSource: string;
            loanOrigin: components["schemas"]["AssumptionOrigin"];
            cityPolicy: components["schemas"]["CityPolicy"];
            reserveMonths: number;
            pressureThresholds: components["schemas"]["PressureThresholds"];
            oldHomeShareThreshold: number;
        };
        CapacityAssumptionsResponse: {
            ruleVersion: string;
            /** Format: date */
            effectiveDate: string;
            ruleSource: string;
            /** @description Compatibility alias for cityPolicy.downPaymentRate. */
            downPaymentRate: number;
            loan: components["schemas"]["LoanParams"];
            loanSource: string;
            loanOrigin: components["schemas"]["AssumptionOrigin"];
            cityPolicy: components["schemas"]["CityPolicy"];
            reserveMonths: number;
            pressureThresholds: components["schemas"]["PressureThresholds"];
            oldHomeShareThreshold: number;
        };
        HousingCapacityResult: {
            netOldHomeProceeds: number;
            deployableCash: number;
            safeTotalPrice: number;
            strainedTotalPrice: number;
            dangerTotalPrice: number;
            downPaymentGap: number;
            monthlyPayment: number;
            monthlyPaymentRatio: number;
            /** @enum {string} */
            pressureLevel: "safe" | "strained" | "danger";
            minimumSafeOldHomeSalePrice: number;
            /** @enum {string} */
            strategy: "先卖后买或同步推进" | "可以同步推进" | "暂缓改善";
            reasons: string[];
            ruleVersion: string;
            effectiveDate: string;
            /** @enum {string} */
            traceabilityStatus: "complete" | "legacy_unversioned";
            appliedAssumptions: components["schemas"]["AppliedAssumptions"] | null;
        };
        CreateCalculationResponse: components["schemas"]["CalculationResponse"];
        CalculationResponse: {
            id: string;
            input: components["schemas"]["HousingCapacityInput"];
            result: components["schemas"]["HousingCapacityResult"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateNeighborhoodRequest: {
            name: string;
            area: string;
            targetLayout: string;
        };
        NeighborhoodResponse: {
            id: string;
            name: string;
            area: string;
            targetLayout: string;
            /** Format: date-time */
            createdAt?: string;
        };
        NeighborhoodSearchResponse: {
            items: components["schemas"]["NeighborhoodResponse"][];
            total: number;
            page: number;
            pageSize: number;
        };
        NeighborhoodMetricResponse: {
            id: string;
            neighborhoodId: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            inventoryCollectionRunId?: string;
            sourceIds: string[];
            /** Format: date-time */
            latestObservedAt: string;
            /** Format: date-time */
            collectedAt: string;
            algorithmVersion: string;
            listedHomes: number;
            priceCutHomes: number;
            avgDaysOnMarket: number | null;
            listingPriceMin?: number | null;
            listingPriceMax?: number | null;
            transactionPriceMin?: number | null;
            transactionPriceMax?: number | null;
            /** @enum {string} */
            transactionMomentum: "unknown" | "weak" | "stable" | "strong";
            transactionEvidence: components["schemas"]["TransactionMomentumEvidence"];
            targetLayoutSupply: number;
            listingSampleCount: number;
            transactionSampleCount: number;
            /** @enum {string} */
            coverage: "full" | "partial";
            /** @enum {string} */
            freshness: "unknown" | "current" | "stale" | "expired";
            /** @enum {string} */
            qualityState: "sufficient" | "low_confidence" | "insufficient_data";
            qualityWarnings: string[];
            /** @enum {string} */
            status: "数据不足" | "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            /** @enum {string} */
            supplyPressure: "unknown" | "low" | "medium" | "high";
            priceCutShare?: number;
            priceGapPct?: number;
            /** @enum {string} */
            targetLayoutScarcity?: "unknown" | "low" | "medium" | "high";
            advice: string;
            reasons?: string[];
            /** Format: date-time */
            calculatedAt: string;
        };
        TransactionMomentumEvidence: {
            /** Format: date */
            windowStart: string;
            /** Format: date */
            windowEnd: string;
            sampleCount: number;
            recent30DayTransactionCount: number;
            preceding60DayTransactionCount: number;
            recent30DayMonthlyFrequency: number;
            preceding60DayMonthlyFrequency: number;
        };
        CollectionRunReference: {
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            dataSourceId: string;
            sourceRef: string;
            /** Format: date-time */
            collectedAt: string;
            /** @enum {string} */
            coverage: "full" | "partial";
        };
        MetricChangeValue: {
            current: number;
            baseline: number;
            absoluteChange: number;
            percentageChange: number | null;
            /** @enum {string} */
            percentageStatus: "available" | "zero_baseline";
        };
        MetricComparison: {
            /** @enum {string} */
            status: "available" | "unavailable";
            /** @enum {string} */
            reason?: "current_partial_coverage" | "full_baseline_not_found" | "transaction_evidence_missing";
            currentBatch: components["schemas"]["CollectionRunReference"];
            baselineBatch?: components["schemas"]["CollectionRunReference"];
            listedHomes?: components["schemas"]["MetricChangeValue"];
            priceCutHomes?: components["schemas"]["MetricChangeValue"];
            recent30DayTransactions?: components["schemas"]["MetricChangeValue"];
        };
        MetricHistoryPoint: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            neighborhoodId: string;
            algorithmVersion: string;
            /** Format: date-time */
            collectedAt: string;
            /** Format: date-time */
            calculatedAt: string;
            /** Format: date-time */
            latestObservedAt: string;
            batch: components["schemas"]["CollectionRunReference"];
            sourceIds: string[];
            listedHomes: number;
            priceCutHomes: number;
            /** @enum {string} */
            transactionMomentum: "unknown" | "weak" | "stable" | "strong";
            transactionEvidence: components["schemas"]["TransactionMomentumEvidence"];
            listingSampleCount: number;
            transactionSampleCount: number;
            /** @enum {string} */
            coverage: "full" | "partial";
            /** @enum {string} */
            freshness: "unknown" | "current" | "stale" | "expired";
            /** @enum {string} */
            qualityState: "sufficient" | "low_confidence" | "insufficient_data";
            qualityWarnings: string[];
            weeklyComparison: components["schemas"]["MetricComparison"];
            monthlyComparison: components["schemas"]["MetricComparison"];
        };
        MetricHistoryResponse: {
            /** @enum {string} */
            status: "ready" | "empty";
            /** Format: uuid */
            neighborhoodId: string;
            algorithmVersion: string;
            window: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            items: components["schemas"]["MetricHistoryPoint"][];
        };
        AddWatchlistItemRequest: {
            neighborhoodId: string;
        };
        AddWatchlistItemResponse: {
            id: string;
            neighborhoodId: string;
            userId: string;
            /** Format: date-time */
            createdAt: string;
        };
        WatchlistResponse: {
            items: components["schemas"]["WatchlistItem"][];
        };
        WatchlistItem: {
            id: string;
            neighborhoodId: string;
            name: string;
            area: string;
            targetLayout: string;
            /** @enum {string} */
            status: "数据不足" | "重点看" | "继续观察" | "适合砍价" | "价格偏硬" | "暂不建议追";
            listedHomes: number | null;
            priceCutHomes: number | null;
            /** @enum {string|null} */
            transactionMomentum: "unknown" | "weak" | "stable" | "strong" | null;
            advice: string;
            hasMetric: boolean;
            /** Format: uuid */
            collectionRunId?: string;
            algorithmVersion?: string;
            sourceIds: string[];
            /** Format: date-time */
            collectedAt: string | null;
            transactionSampleCount: number | null;
            /** @enum {string} */
            coverage: "unknown" | "full" | "partial";
            /** @enum {string} */
            freshness: "unknown" | "current" | "stale" | "expired";
            /** @enum {string} */
            qualityState: "sufficient" | "low_confidence" | "insufficient_data";
            qualityWarnings: string[];
            /** @description Compares the current metric with the latest full-coverage batch collected in the inclusive [T-14 days, T-7 days] window, where T is currentBatch.collectedAt. */
            weeklyComparison: components["schemas"]["MetricComparison"] | null;
        };
        ActionWindowResponse: {
            /**
             * @example 砍价
             * @enum {string}
             */
            action: "看" | "等" | "砍价" | "出手";
            /**
             * @example 高
             * @enum {string}
             */
            confidence: "低" | "中" | "高";
            /** @example 预算仍可服务，且目标小区供应与降价信号支持买方试探底价。 */
            summary: string;
            /**
             * @example [
             *       "约看 3 套成交区间附近、挂牌超过 60 天的目标户型。"
             *     ]
             */
            checklist: string[];
            /**
             * @example [
             *       "预算不是完全宽松，砍价失败时不要上调总价硬追。"
             *     ]
             */
            risks: string[];
        };
        AccessStatusResponse: {
            /** @enum {string} */
            status: "unlocked";
        };
        CreateDataSourceRequest: {
            name: string;
            sourceType: string;
            city: string;
            notes?: string;
        };
        DataSource: {
            /** Format: uuid */
            id: string;
            name: string;
            sourceType: string;
            city: string;
            notes: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ImportJSONRequest: {
            /** Format: uuid */
            dataSourceId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRef: string;
            /** Format: date-time */
            collectedAt: string;
            /** @enum {string} */
            coverage: "full" | "partial";
            records: components["schemas"]["ImportJSONRecord"][];
        };
        ImportJSONRecord: {
            /** @enum {string} */
            recordType: "listing" | "transaction";
            sourceRecordId: string;
            layout: string;
            areaSqm: number;
            listingPrice?: number;
            transactionPrice?: number;
            /** Format: date */
            transactionDate?: string;
            daysOnMarket?: number;
            /** @enum {string} */
            status?: "active" | "pending" | "withdrawn" | "sold";
            originalListingRef?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        CollectionRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dataSourceId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRef: string;
            /** Format: date-time */
            collectedAt: string;
            /** @enum {string} */
            coverage: "full" | "partial";
            /** @enum {string} */
            format: "json" | "csv";
            contentChecksum: string;
            rawContentType: string;
            validationSummary: components["schemas"]["ValidationSummary"];
            /** @enum {string} */
            status: "completed";
            /** @enum {string} */
            metricStatus: "pending" | "completed" | "failed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ValidationSummary: {
            recordCount: number;
            listingCount: number;
            transactionCount: number;
            issues: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            row?: number;
            field: string;
            code: string;
            message: string;
        };
        ImportCollectionRunResponse: {
            /** Format: uuid */
            collectionRunId: string;
            acceptedRecordCount: number;
            rejectedRecordCount: number;
            collectionRun: components["schemas"]["CollectionRun"];
            listingObservationCount: number;
            transactionObservationCount: number;
            idempotentReplay: boolean;
            /** @enum {string} */
            metricRefreshStatus: "pending" | "completed" | "failed";
        };
        ListingObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceListingId: string;
            sourceRow: number;
            layout: string;
            areaSqm: number;
            /** @description 万元 */
            listingPrice: number;
            daysOnMarket: number;
            /** @enum {string} */
            status: "active" | "pending" | "withdrawn" | "sold";
            /** Format: date-time */
            capturedAt: string;
            attributes: {
                [key: string]: string;
            };
        };
        TransactionObservation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            collectionRunId: string;
            /** Format: uuid */
            neighborhoodId: string;
            sourceRecordId: string;
            sourceRow: number;
            layout: string;
            areaSqm: number;
            /** @description 万元 */
            transactionPrice: number;
            /** Format: date */
            transactionDate: string;
            originalListingRef?: string;
            /** Format: date-time */
            capturedAt: string;
        };
        CollectionRunDetail: {
            collectionRun: components["schemas"]["CollectionRun"];
            source: components["schemas"]["DataSource"];
            listings: components["schemas"]["ListingObservation"][];
            transactions: components["schemas"]["TransactionObservation"][];
            /** Format: byte */
            rawPayloadBase64: string;
        };
        ValidationErrorResponse: {
            error: {
                /** @enum {string} */
                code: "validation_failed";
                message: string;
                details: components["schemas"]["ValidationIssue"][];
            };
        };
        ImportValidationErrorResponse: {
            error: {
                /** @enum {string} */
                code: "validation_failed";
                message: string;
                details: components["schemas"]["ValidationIssue"][];
            };
            /** @enum {integer} */
            acceptedRecordCount: 0;
            rejectedRecordCount: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Valid bearer access token is required */
        AccessRequired: {
            headers: {
                /**
                 * @description Authentication scheme required to access this operation
                 * @example Bearer
                 */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "access_required",
                 *         "message": "valid bearer access token is required"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
